name: dartcraft
description: A modern, cross-platform Minecraft launcher library for Dart and Flutter applications. Supports game installation, version management, user authentication, and launching.
version: 1.0.0
repository: https://github.com/yourusername/dartcraft
issue_tracker: https://github.com/yourusername/dartcraft/issues
documentation: https://pub.dev/documentation/dartcraft

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.8.0+1
  http: ^1.4.0
  crypto: ^3.0.3
  archive: ^3.4.0
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

topics:
  - minecraft
  - launcher
  - game
  - cross-platform
  - authentication

funding:
  - https://github.com/sponsors/yourusername
