name: dartcraft
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  http: ^1.4.0
  crypto: ^3.0.3
  archive: ^3.4.0
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
